version: '3.1'

services:

  postgres:
    container_name: db_container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin